name: Build

on:
  push:
    branches:
      - "**"

jobs:
  release:
    uses: mathisdt/workflows/.github/workflows/maven.yaml@master
    with:
      script-after-maven-build: ./build-jre-distributions.sh
      pattern-to-release: name-checker-*.zip
    secrets: inherit
